### PR TITLE
Implemented Arbitrary derivation for Scala enums

### LINKED ISSUE #56: Derivation of Arbitrary instances for scala.Enumerations
E.g. given:
```scala
object WeekDay extends Enumeration {
  val Mon, Tue, Wed, Thu, Fri, Sat, Sun = Value
}
```
it should be possible to derive `Arbitrary[WeekDay.Value]`.

The implementation is a one-liner:
```scala
implicit def arbEnum[E <: Enumeration](implicit enum: Witness.Aux[E]): Arbitrary[E#Value] =
  Arbitrary(Gen.oneOf(enum.value.values.toSeq))
```

Happy to make a PR if this fits in the library.

### PR DESCRIPTION
**Pull request by joroKr21**
Resolves #56

### CODE REVIEW

**Comment by alexarchambault** [comment]
Thanks for that!

I'm not sure the enumeration-specific things should go into `MkArbitrary` (which is more for the case class / sealed hierarchy things, that is things that `shapeless.Generic` genericizes). An `EnumerationInstances` would be more suited, a bit like the current `SingletonInstances` or `FieldTypeInstances`. `EnumerationInstances` would then be mixed into `org.scalacheck.Shapeless` too.

**Comment by joroKr21** [comment]
Ok, moved the definition to trait `EnumerationInstances` as suggested.

**Comment by alexarchambault** [comment]
Looks great, thanks!

**Comment by alexarchambault** [comment]
`1.1.5` (which includes this) just released.

**Pull request merged**
