### PR TITLE
Update artifact version in the readme

### PR DESCRIPTION
**Pull request by BenFradet**

### CODE REVIEW

**Comment by alexarchambault** [comment]
Thanks!

The extra repository is still useful though. When the scalacheck-shapeless artifacts are just released, it  can sometimes take a few hours before they show up on Maven Central, but they are available straightaway on Sonatype releases. So I'd prefer keeping manually adding the latter just in case.

**Comment by BenFradet** [comment]
Ok, I'll revert that part adding a comment describing why one would need it :+1:

**Comment by BenFradet** [comment]
done :+1:

**Comment by alexarchambault** [comment]
Thanks, merging!

**Pull request merged**
