### PR TITLE
Update docs for import's.

### PR DESCRIPTION
**Pull request by kevinmeredith**

### CODE REVIEW

**Comment by kevinmeredith** [comment]
Bump :)

**Comment by alexarchambault** [comment]
@kevinmeredith It should still be `org.scalacheck.ScalacheckShapeless` (works since `1.1.6`). Ok with the import of `Arbitrary` though :-)

**Comment by kevinmeredith** [comment]
Could you please say more on `Ok with the import of Arbitrary though `?

Also - thanks for this great library!

**Comment by alexarchambault** [comment]
Oops, sorry for the late answer :\

I meant adding the `import org.scalacheck.Arbitrary` line is ok. But `import org.scalacheck.ScalacheckShapeless` shoudn't be changed, as it works since `1.1.6` (and `org.scalacheck.Shapeless` was deprecated).

**Comment by timvw** [comment]
I ran into this not-working import as well. It is because the start of the page starts with importing version 1.1.5... So the really fix is replacing it with 1.1.6 ;)

**Pull request closed without merging**
