### PR TITLE
Update scala-cli to 1.4.1 to update Scala Native to 0.5.x

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by sideeffffect** [comment]
@alexarchambault can you please run again? :pray:

**Comment by sideeffffect** [comment]
We're green :tada: can you please merge and make a new release @alexarchambault ? :pray:

**Review by alexarchambault — APPROVED** [review]
Thanks @sideeffffect!

**Comment by sideeffffect** [comment]
Can we also have a new release, please? :pleading_face:

**Comment by sideeffffect** [comment]
The publish has failed :crying_cat_face: 
https://github.com/alexarchambault/scalacheck-shapeless/actions/runs/10076647801

**Comment by alexarchambault** [comment]
@sideeffffect Yeah, I just manually finished it via the Sonatype UI

**Pull request merged**
