### PR TITLE
bump ScalaCheck version (1.14.0->3)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
no idea why this fails, didn't attempt to investigate. perhaps a regression in ScalaCheck?

this came up in the Scala 2.13 community build

**Comment by alexarchambault** [comment]
I didn't investigate yet, but I think things around `Gen.resize` may have changed in scalacheck, which breaks the way recursion is handled in some cases in scalacheck-shapeless.

**Comment by alexarchambault** [comment]
Managed to make the tests pass in https://github.com/alexarchambault/scalacheck-shapeless/pull/152.

**Comment by SethTisue** [comment]
scala/community-build@d45c3438f205a4ed7f6a3b03750555b7aa45e883 :+1:

**Pull request closed without merging**
